### PR TITLE
Pretty print imports

### LINKED ISSUE #242: Fix formatting of long import lists
As suggested by @bergmark in https://github.com/chrisdone/hindent/issues/228#issuecomment-243302011.

### PR DESCRIPTION
**Pull request by adamse**
Fixes #242.

### CODE REVIEW

**Comment by chrisdone** [comment]
Looks good.

**Comment by sighingnow** [comment]
LGTM.

Sorry for the late response. Could you rebase to HEAD and resolve conflicts so that we can merge this patch ?

**Comment by adamse** [comment]
@sighingnow done and done!

**Comment by sighingnow** [comment]
Merged. Thanks for your patch :clap::clap:

**Comment by bergmark** [comment]
Thank you! 🎉

**Pull request merged**
