### PR TITLE
Switch from descriptive to optparse-applicative

### PR DESCRIPTION
**Pull request by purcell**
Aiming to get hindent back into Stackage Nightly (and, soon, LTS with GHC 8.4), I contacted @chrisdone via Twitter to see if I could help. Chris indicated he planned to switch `hindent` from `descriptive` to `optparse-applicative`. This is that change, though I'm not 100% sure it's perfect yet as I haven't exhaustively tested it. Hope this helps.

### CODE REVIEW

**Comment by purcell** [comment]
Build seems content after a couple of force-pushes to allow for older GHC/LTS compatibility. :-)

**Comment by chrisdone** [comment]
Looks good! Thanks Steve. I'll try this out locally.

**Comment by chrisdone** [comment]
Everything seems to work apart from extension passing:
```
chris@precision:~/Emacs/packages/hindent$ echo 'x=1' | stack exec -- hindent -XRecursiveDo
option -X: cannot parse value `RecursiveDo'
```

It's because `auto` uses the `Read` instance for `Text` which expects double quotes. I switched it to `strOption`. :+1:

**Comment by chrisdone** [comment]
Going to bump version and push to hackage.

**Comment by purcell** [comment]
> Everything seems to work apart from extension passing

Doh, thanks!

> Going to bump version and push to hackage.

Yay! :-)

**Pull request merged**
