### PR TITLE
Reports the SrcLoc if there is a parser error

### LINKED ISSUE #326: hindent doesn't report source location in case of syntax error
I ran into a syntax error and all hindent said was:

hindent: Parse error: rec

in a 700+ line file with multiple matches for 'rec'. It would be really helpful if it was more specific about where exactly the parse error occurred.

### PR DESCRIPTION
**Pull request by adamse**
Fixes #326

### CODE REVIEW

**Comment by NorfairKing** [comment]
+1 Great idea.

**Comment by adamse** [comment]
Perhaps we don't want to say the filename in the parse error?

Currently
```
<unknown>.hs: 1: 21: Parse error: EOF
```

but perhaps 
```
<unknown>.hs: 1: 21: Parse error: EOF

**Comment by adamse** [comment]
Whoops accidentally closed this one.

**Comment by adamse** [comment]
Is this patch acceptable or do you require any changes? @sighingnow

**Comment by sighingnow** [comment]
Merged. I must apologize for responding so late. Thanks for your contribution @adamse .

**Pull request merged**
